baseurl = "https://bowmansolutions.com/"
copyright = "Copyright 2015 Jonathan Bowman. All documentation and code contained on this site may be freely shared in compliance with [the Apache License, Version 2.0](http://www.apache.org/licenses/LICENSE-2.0), and is **provided \"AS IS\" without warranties or conditions of any kind**."
languageCode = "en-us"
title = "Bowman Solutions"
pluralizeListTitles = false
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Website for Bowman Solutions"
  author = "Jonathan Bowman"
